AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*_test.rb'

Lint/EmptyBlock:
  Exclude:
    - 'test/**/*_test.rb'

Naming/VariableNumber:
  Exclude:
    - 'test/**/*_test.rb'
