name: continuous-integration
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.7' ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ruby }}-gem-
      - name: Install gems
        run: |
          sed -i '/ruby ".*"/,+1 d' Gemfile
          bundle_version=`awk '/BUNDLED WITH/{getline; gsub(/ /, "", $0); print}' Gemfile.lock`
          gem install bundler --no-document -v ${bundle_version}
          bundle config retry "3"
          bundle config jobs "$(nproc)"
          bundle config path vendor/bundle
          bundle install
      - name: Run RuboCop
        run: bundle exec rubocop --parallel
      - name: Run tests
        run: bundle exec rake test
